CREATE TABLE `stock_ths_gn_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `gn_name` varchar(32) DEFAULT NULL COMMENT '概念名',
  `gn_code` varchar(32) DEFAULT NULL COMMENT '概念的code',
  `stock_code` varchar(32) DEFAULT NULL COMMENT '股票code',
  `stock_name` varchar(32) DEFAULT NULL COMMENT '股票名',
  `stock_price` decimal(12,3) DEFAULT NULL COMMENT '现价',
  `stock_change` decimal(6,2) NOT NULL COMMENT '涨跌幅（单位百分比：%）',
  `stock_change_price` decimal(6,2) DEFAULT NULL COMMENT '涨跌价格',
  `stock_change_speed` decimal(6,2) DEFAULT NULL COMMENT '涨跌速（单位百分比：%）',
  `stock_handover_scale` decimal(6,2) DEFAULT NULL COMMENT '换手率（单位百分比：%）',
  `stock_liang_bi` decimal(6,2) DEFAULT NULL COMMENT '量比',
  `stock_amplitude` decimal(6,2) DEFAULT NULL COMMENT '振幅（单位百分比：%）',
  `stock_deal_amount` decimal(12,4) DEFAULT NULL COMMENT '成交额(单位：万)',
  `stock_flow_stock_number` decimal(12,4) DEFAULT NULL COMMENT '流通股票量（单位:万）',
  `stock_flow_makert_value` decimal(20,4) DEFAULT NULL COMMENT '流通市值（单位：万）',
  `stock_market_ttm` decimal(12,4) DEFAULT NULL COMMENT '市盈率',
  `crawler_time` varchar(64) DEFAULT NULL COMMENT '发起抓取时间',
  `crawler_version` varchar(128) DEFAULT NULL COMMENT '当前抓取的版本',
  `some_ext` longtext COMMENT '扩展数据',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_gn_name` (`gn_name`),
  KEY `idx_gn_code` (`gn_code`),
  KEY `idx_stock_code` (`stock_code`),
  KEY `idx_stock_name` (`stock_name`),
  KEY `idx_stock_price` (`stock_price`),
  KEY `idx_stock_change` (`stock_change`),
  KEY `idx_stock_change_price` (`stock_change_price`),
  KEY `idx_stock_change_speed` (`stock_change_speed`),
  KEY `idx_stock_handover_scale` (`stock_handover_scale`),
  KEY `idx_stock_liang_bi` (`stock_liang_bi`),
  KEY `idx_stock_amplitude` (`stock_amplitude`),
  KEY `idx_stock_deal_amount` (`stock_deal_amount`),
  KEY `idx_stock_flow_stock_number` (`stock_flow_stock_number`),
  KEY `idx_stock_flow_makert_value` (`stock_flow_makert_value`),
  KEY `idx_stock_market_ttm` (`stock_market_ttm`),
  KEY `idx_crawler_time` (`crawler_time`),
  KEY `idx_crawler_version` (`crawler_version`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_update_time` (`update_time`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='同花顺的概念个股数据';